export const data = [
  {
    id: 0,
    imgUrl: "./logos/react.svg",
    label: "React.js",
    matched: false,
  },
  {
    id: 1,
    imgUrl: "./logos/angular.svg",
    label: "Angular.js",
    matched: false,
  },
  {
    id: 2,
    imgUrl: "./logos/aws.svg",
    label: "AWS",
    matched: false,
  },
  {
    id: 3,
    imgUrl: "./logos/docker.svg",
    label: "Docker",
    matched: false,
  },
  {
    id: 4,
    imgUrl: "./logos/firebase.svg",
    label: "Firebase",
    matched: false,
  },
  {
    id: 5,
    imgUrl: "./logos/git.svg",
    label: "Git",
    matched: false,
  },
  {
    id: 6,
    imgUrl: "./logos/github.svg",
    label: "Github",
    matched: false,
  },
  {
    id: 7,
    imgUrl: "./logos/html.svg",
    label: "HTML",
    matched: false,
  },
  {
    id: 8,
    imgUrl: "./logos/js.svg",
    label: "JS",
    matched: false,
  },
  {
    id: 9,
    imgUrl: "./logos/next.svg",
    label: "Next.js",
    matched: false,
  },
  {
    id: 10,
    imgUrl: "./logos/python.svg",
    label: "Python.js",
    matched: false,
  },
  {
    id: 11,
    imgUrl: "./logos/tailwind.svg",
    label: "Tailwind CSS",
    matched: false,
  },
  {
    id: 12,
    imgUrl: "./logos/vs-code.svg",
    label: "VS Code",
    matched: false,
  },
  {
    id: 13,
    imgUrl: "./logos/vue.svg",
    label: "Vue.js",
    matched: false,
  },
  {
    id: 14,
    imgUrl: "./logos/webstorm.svg",
    label: "Webstorm",
    matched: false,
  },
];
